import { StepType } from '@/lib/types'

type Step = {
  order: number
  type: StepType
  tool: string | null
  title: string
  description: string
  prompt: string | null
}

const TYPE_LABELS: Record<StepType, string> = {
  TRIGGER: 'Trigger',
  AI: 'AI Step',
  HUMAN: 'Human Step',
  INTEGRATION: 'Integration',
  OUTPUT: 'Output',
}

function getImplementationNote(step: Step): string {
  const tool = step.tool
  switch (step.type) {
    case 'TRIGGER':
      return tool
        ? `**In Make.com:** Search for "${tool}" → choose a watch/trigger event matching "${step.title}" → connect your ${tool} account.`
        : `**In Make.com:** Use "Webhooks → Custom Webhook" as the trigger. Copy the webhook URL and use it to fire this workflow.`
    case 'AI':
      return `**In Make.com:** Add "OpenAI → Create a Chat Completion" and paste the prompt below into the message content. To use Claude, add an "HTTP → Make a Request" module calling https://api.anthropic.com/v1/messages with your Anthropic API key.`
    case 'HUMAN':
      return `**Manual step:** A team member must complete "${step.title}" before the workflow continues.${tool ? ` Use ${tool} to do this.` : ''} Add an email or Slack notification module before this step so the right person is alerted.`
    case 'INTEGRATION':
      return tool
        ? `**In Make.com:** Search for "${tool}" → find an action matching "${step.title}" → connect your ${tool} account and map the input fields from the previous step.`
        : `**In Make.com:** Use "HTTP → Make a Request" to call the relevant API for "${step.title}".`
    case 'OUTPUT':
      return tool
        ? `**In Make.com:** Add a "${tool}" action to send or store the final output. Map the content from the AI or integration step above.`
        : `**Final step:** Add a Send Email, Slack Message, or storage action to deliver the result.`
  }
}

export function generateSetupGuide(workflow: {
  taskName: string
  summary: string | null
  department: string
  steps: Step[]
}): string {
  const lines: string[] = []

  lines.push(`# Workflow: ${workflow.taskName}`)
  lines.push(`**Department:** ${workflow.department}`)
  if (workflow.summary) lines.push(`**Summary:** ${workflow.summary}`)
  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push('## How to implement this workflow')
  lines.push('')
  lines.push(
    'Follow these steps as a manual checklist, or use them as a blueprint to build an automated scenario in Make.com, Zapier, or n8n. ' +
    'Each step includes what to do and how to set it up in an automation tool.'
  )
  lines.push('')
  lines.push('> **Note:** Whichever tool you use, you will need to connect your accounts (e.g. Zendesk, HubSpot) and replace placeholders like `[CUSTOMER NAME]` and `[TICKET CONTENT]` with actual data fields from your trigger.')
  lines.push('')

  const sorted = [...workflow.steps].sort((a, b) => a.order - b.order)

  for (const step of sorted) {
    lines.push(`---`)
    lines.push('')
    lines.push(`### Step ${step.order + 1} · ${TYPE_LABELS[step.type]}: ${step.title}`)
    if (step.tool) lines.push(`**Tool:** ${step.tool}`)
    lines.push('')
    lines.push(step.description)
    lines.push('')
    lines.push(getImplementationNote(step))
    lines.push('')

    if (step.type === 'AI' && step.prompt) {
      lines.push('**Prompt:**')
      lines.push('')
      lines.push('```')
      lines.push(step.prompt)
      lines.push('```')
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('')
  lines.push('*Generated by AuditAI*')

  return lines.join('\n')
}
